### ISSUE TITLE
Dismiss on touch

### ISSUE THREAD

**Issue by HTCDeveloper** [JoeFryer/JDFTooltips#14]
Dismiss on touch doesn't work, i think it's because it's drawing using Brezier Line Path, and has a clear color as the background, so the touchgesture never gets firedinside of the rectangle

**Comment by JoeFryer** [comment]
Hi @HTCDeveloper - thanks for reporting this. I'll investigate when I'm back at my computer.

**Comment by JoeFryer** [comment]
@HTCDeveloper - I can't reproduce this. Do you have any more details?
