### ISSUE TITLE
Can't run pod install from Example directory

### ISSUE THREAD

**Issue by haabaato** [JoeFryer/JDFTooltips#2]
Here's what I get when I try to install the dependencies.

```
$ pod install
Analyzing dependencies

CocoaPods 0.36.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Fetching podspec for `JDFTooltips` from `../`
[!] Unable to satisfy the following requirements:

- `JDFTooltips (from `../`)` required by `Podfile`
- `JDFTooltips (from `../`)` required by `Podfile`
- `JDFTooltips (= 0.1.0)` required by `Podfile.lock`
```

Regardless, I've managed to integrate your library into my app, and was wondering if you had plans to support the following:
- customization of tooltip views, primarily padding
- showing the same tooltip more than once
- animation customization

I could also try implementing these myself and submitting a pull request if you'd like.

**Comment by JoeFryer** [comment]
Hi @haabaato,

It seems as though the `podfile.lock` was out of sync for the example project (it was referencing `JDFTooltips v0.1.0`, where it should have been `v1.0`. Deleting the `Podfile.lock` and running `pod install` again fixes it. I had also referenced the pod files in the workspace (meaning there were duplicate symbols), so I've fixed that as well (I'll push the fix now).

Great - I hope you find it useful. I have a few plans to expand the library, including customising the tooltips and animations. Re showing the same tooltip twice; you should be able to do that already (unless I'm not understanding exactly what you mean).

In any case, I plan to get around to adding new features at some point, but in the meantime feel free to implement them yourself and submit a pull request; that would be very much appreciated! You could open issues for stuff if you wanted.

Cheers,

Joe
