### ISSUE TITLE
Text shows after tooltip is shown

### ISSUE THREAD

**Issue by mzekrallah** [JoeFryer/JDFTooltips#5]
Thanks for the great library. it's really well written and architected. One issue though is that the text is always some milliseconds behind when showing the tooltip. I mean the tooltip background shows first and after that the text appears. the same when dismissing. You can see it in the demo picture on the home page. 

Is this intentional or is it a bug ? visually it looks like an issue.. if you got a quick hack to fix it, please help. Thank you

**Comment by JoeFryer** [comment]
Thanks very much!

I did that intentionally; I thought it looked a bit better (less jarring, and more fluid, maybe?). I'm open to suggestion though. I've just added a new branch (`alternate_animation`) - check it out and have a look, let me know what you think.

**Comment by mzekrallah** [comment]
Awesome .. that branch is much more better ! Thanks .. I also think if you can make the popup have a growing animation in (Show) action like the one in (dismiss) action it would be great ! Also, the tooltip arrow should be a bit smaller to make it look like flat UI design. Something similar to this https://github.com/teodorpatras/EasyTipView

**Comment by JoeFryer** [comment]
I've merged the new animation in now, so I'm closing this issue.
