### ISSUE TITLE
Two tooltips when I should be getting one

### ISSUE THREAD

**Issue by anuchandra** [JoeFryer/JDFTooltips#8]
I'm getting two tooltips when I should be getting one. I have a tableview which contains a imageview and a contentview. The contentview has a button. I'd like to show the tooltip pointing to the button. The code below tries to do that. Could you point me where I'm going wrong?
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath object:(PFObject *)object {
  
  static NSString *CellIdentifier = @"Cell";  
  JKEPFTableViewCell *cell = (JKEPFTableViewCell *)[tableView dequeueReusableCellWithIdentifier:CellIdentifier];
  if (cell == nil) {
      cell = [[JKEPFTableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:CellIdentifier];
  }
  
  // Configure the cell
  ...
  UIView _contentView = (UIView_) [cell viewWithTag:105];
  JDFTooltipView *tooltip = [[JDFTooltipView alloc] initWithTargetView:cell.shortlistButton hostView:contentView tooltipText:@"Tap to find similar shoes" arrowDirection:JDFTooltipViewArrowDirectionUp width:200.0f];
  [tooltip show];
  ...  
  return cell;
  }

![simulator screen shot 31 jan 2016 22 38 32](https://cloud.githubusercontent.com/assets/10838956/12705554/ac787f72-c86b-11e5-874b-d7f488713d18.png)

**Comment by JoeFryer** [comment]
The reason you're getting 2 tooltips is because you are creating/showing it in cel cellForRowAtIndexPath - this can be called more than once.

**Comment by anuchandra** [comment]
That's extremely well spotted and easily fixed. Thanks.

**Comment by JoeFryer** [comment]
No problem - glad I could help. I'll close this Issue.
